server:
  port: 8020

spring:

  application:
    name: second-microservice

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/custom-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    enabled: true
    oauth:
      client-id: first-app
      client-secret: oBpEImuoqtjWRzFgrqtApmEXvI8uzHIq

logging:
  level:
    org:
      springframework:
        security: DEBUG
